version: '3.9'
services: 
  db: 
    image: postgres:14.1
    environment:
      POSTGRES_USER: fullstack
      POSTGRES_PASSWORD: fullstack
      DEV_DB: fullstack_dev
    volumes:
      #- ./pgdata:/var/lib/postgresql/data
      - ./Docker/create_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
  web:
    command: npm run dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    depends_on:
      - db
    ports: 
      - "4000:4000"